rango/urls.py
from django.urls import path
from rango.views import AboutView, AddCategoryView, \
    IndexView, AddPageView, RestrictedView, ShowCategoryView, \
    GotoUrlView, RegisterProfileView, ProfileView, ListProfileView, \
    LikeCategoryView, CategorySuggestionView, AddPageSearchView

app_name = 'rango'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('category/<slug:category_name_slug>/', ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', AddPageView.as_view(), name='add_page'),
    path('restricted/', RestrictedView.as_view(), name='restricted'),
    path('goto/', GotoUrlView.as_view(), name='goto'),
    path('register_profile/', RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
    path('profiles/', ListProfileView.as_view(), name='list_profiles'),
    path('like_category/', LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', CategorySuggestionView.as_view(), name='suggest'),
    path('search_add_page/', AddPageSearchView.as_view(), name='search_add_page'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.contrib import admin
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)

        if self.views < 0:
            self.views = 0

        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(blank=True)

    def save(self, *args, **kwargs):
        self.last_visit = timezone.now()
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class PageAdmin(admin.ModelAdmin):
    list_display = ('title', 'category', 'url')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from rango.forms import CategoryForm, PageForm, UserProfileForm
from rango.models import Category, Page, UserProfile
from rango.bing_search import run_query
import rango.helpers as hp
from rango.TopFiveCategoriesFromModels import TopFiveCategoriesFromModels


class IndexView(View):
    def get(self, request):

        page_list = Page.objects.order_by('-views')[:5]

        categories = TopFiveCategoriesFromModels(Category)
        category_list = categories.get_list_of_top_5_categories()

        context_dict = dict()
        context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
        context_dict['categories'] = category_list
        context_dict['pages'] = page_list

        if hasattr(request, 'session'):
            hp.visitor_cookie_handler(request)

        return render(request, 'rango/index.html', context=context_dict)


class AboutView(View):
    def get(self, request):
        context_dict = dict()

        if hasattr(request, 'session'):
            hp.visitor_cookie_handler(request)
            context_dict['visits'] = request.session['visits']

        context_dict['boldmessage'] = 'This tutorial has been put together by Amy Gillies.'

        return render(request, 'rango/about.html', context_dict)


class ShowCategoryView(View):
    context_dict = dict()
    result_list = []

    def get_data(self, category_name_slug):
        try:
            category = Category.objects.get(slug=category_name_slug)
            pages = Page.objects.filter(category=category).order_by('-views')

            self.context_dict['pages'] = pages
            self.context_dict['category'] = category

        except Category.DoesNotExist:
            self.context_dict['category'] = None
            self.context_dict['pages'] = None

    def get(self, request, category_name_slug):
        self.get_data(category_name_slug)
        self.context_dict['result_list'] = self.result_list
        return render(request, 'rango/category.html', context=self.context_dict)

    @method_decorator(login_required)
    def post(self, request):
        query = request.POST['query'].strip()
        if query:
            self.context_dict['query'] = query
            self.context_dict['result_list'] = run_query(query)

        return render(request, 'rango/category.html', context=self.context_dict)


class AddCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

        return render(request, 'rango/add_category.html', {'form': form})


class AddPageView(View):
    form = PageForm()
    category = None
    context_dict = dict()

    def get_category(self, category_name_slug):
        try:
            self.category = Category.objects.get(slug=category_name_slug)
            self.context_dict['category'] = self.category
        except Category.DoesNotExist:
            self.category = None

        if self.category is None:
            return redirect(reverse('rango:index'))

    @method_decorator(login_required)
    def get(self, request, category_name_slug):
        self.get_category(category_name_slug)
        self.context_dict['form'] = self.form
        return render(request, 'rango/add_page.html', self.context_dict)

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        self.get_category(category_name_slug)
        self.form = PageForm(request.POST)

        if self.form.is_valid():
            if self.category:
                page = self.form.save(commit=False)
                page.category = self.category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug': category_name_slug}))
            else:
                print(self.form.errors)
                self.context_dict['form'] = self.form
                return render(request, 'rango/add_page.html', context=self.context_dict)


class RestrictedView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'rango/restricted.html',
                      context={'message': "Since you're logged in, you can see this text!"})


class GotoUrlView(View):
    def get(self, request):
        page_id = request.GET.get('page_id')

        try:
            page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))

        page.views += 1
        page.last_visit = timezone.now()
        page.save()

        return redirect(page.url)


class RegisterProfileView(View):
    form = UserProfileForm
    context_dict = dict()

    def get(self, request):
        self.context_dict['form'] = self.form
        return render(request, 'rango/profile_registration.html', context=self.context_dict)

    def post(self, request):
        self.form = UserProfileForm(request.POST, request.FILES)

        if self.form.is_valid():
            user_profile = self.form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
        else:
            print(self.form.errors)

        return redirect(reverse('rango:index'))


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture})

        return user, user_profile, form

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'rango/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        return render(request, 'rango/profile.html', context_dict)


class ListProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request, 'rango/list_profiles.html', {'user_profile_list': profiles})


class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        category.likes = category.likes + 1
        category.save()
        return HttpResponse(category.likes)


class CategorySuggestionView(View):
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''

        category_list = hp.get_category_list(8, suggestion)

        if len(category_list) == 0:
            category_list = Category.objects.order_by('-likes')

        return render(request, 'rango/categories.html', {'categories': category_list})


class AddPageSearchView(View):
    @method_decorator(login_required)
    def get(self, request):
        categoryId = request.GET['categoryId']
        title = request.GET['title']
        url = request.GET['url']

        try:
            category = Category.objects.get(id=categoryId)
        except Category.DoesNotExist:
            return HttpResponse('Error - category not found.')
        except ValueError:
            return HttpResponse('Error - bad category ID.')

        Page.objects.get_or_create(category=category, title=title, url=url)
        pages = Page.objects.filter(category=category).order_by('-views')

        return render(request, 'rango/page_list.html', {'pages': pages})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Rango says...</h1>
            <div>
                <h2 class="h2">
                    here is the about page.
                </h2>
                <strong>{{ boldmessage }}</strong>
            </div>
        </div>
    </div>

    <center><div>
        <div>
            <button class="btn btn-primary"
                    onclick="alert('You clicked the button using inline JavaScript.');">
                Click me - I run on vanilla JavaScript!
            </button>
        </div>
        <br />
        <div>
            <button class="btn btn-primary" id="about-btn">
                Click me - I'm using JQuery!
            </button>
        </div>
    </div></center>

    <br />

    <center><div class="container">
        <div class="row">

            <div class="col-md-6">
                <div class="card mb-6">
                    <div class="card-body">
                        <center><img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /></center>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-6">
                     <div class="card body">
                         <center><img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." height="240" width="400" /></center>
                     </div>
                </div>
            </div>
        </div>
    </div></center>

    <div>
        <p>Visits: {{ visits }}</p>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Category</h1>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <form role="form" id="category_form" method="post"
                  action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                    <div class="p-2"></div>
                {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Category
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Page
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Page to {{ category.name }}</h1>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <form role="form" id="page_form" method="post"
                  action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }} <br />
                    <div class="p-2"></div>
                {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Page
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>

    <head lang="en">
        <meta charset="UTF-8"/>
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>

    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>

        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>

        <hr />

        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                    <li><a href="{% url 'auth_password_change' %}">Password Change</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>

</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">

                    <div class="w-75 ml-3">
                            <input type="search" id="search-input"
                                   class="form-control ds-input" placeholders="Search..."/>
                    </div>

                    <div class="sidebar-sticky" id="categories-listing">
                        {% block sidebar_block %}
                            {% get_category_list category %}
                        {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{ c.name }}
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{ c.name }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            {% if category %}
                <h1 class="jumbotron-heading">{{ category.name }}</h1>

                <div>
                    <strong id="like_count">{{ category.likes }}</strong> likes
                    {% if user.is_authenticated %}
                        <button id="like_btn"
                            data-categoryid="{{ category.id }}"
                            class="btn btn-primary btn-sm"
                            type="button">
                            <span data-feather="thumbs-up"></span>
                            Like Category
                        </button>
                    {% endif %}
                </div>

            {% else %}
                <h1 class="jumbotron-heading">The specified category does not exist.</h1>
            {% endif %}
        </div>
    </div>

    {% if category %}
        <div id="pages">
            {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                        <span class="tag tag-pill tag-primary">
                            {% if page.views > 1 %}
                                {{ page.views }} views
                            {% elif page.views == 0 %}
                                No views
                            {% else %}
                                {{ page.views }} view
                            {% endif %}
                        </span></li>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>No pages currently in category.</strong>
            {% endif %}
        </div>
        <br />

        {% if user.is_authenticated %}
            <div>
                <form class="form-inline" id="user-form" method="post"
                      action="{% url 'rango:show_category' category.slug %}">
                    {% csrf_token %}

                    <div class="form-group">
                        <input class="form-control" type="text" size="50"
                               name="query" id="query" value="{{ query_search }}"/>
                    </div>

                    <button class="btn btn-primary" type="submit" name="submit">Search</button>
                </form>
            </div>

            <div>
                {% if result_list %}
                    <h2>Results</h2>

                    <div class="list-group" id="list-page">
                        {% for result in result_list %}
                            <div class="list-group-item">
                                <h3 class="list-group-item-heading">
                                    <a href="{{ result.link }}">
                                        {{ result.title|safe|escape }}
                                    </a>
                                </h3>
                                <p class="list-group-item-text">
                                    {{ result.summary|safe|escape }}
                                </p>
                                <button class="btn btn-primary btn-sm add_page_btn" type="button"
                                     data-title="{{ result.title }}" data-url="{{ result.link }}"
                                     data-categoryid="{{ category.id }}">
                                    Add Page
                                </button>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/rango/page_list.html
{% if pages %}
    <ul>
        {% for page in pages %}
            <li>
                <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                <span class="tag tag-pill tag-primary">
                    {% if page.views > 1 %}
                        {{ page.views }} views
                    {% elif page.views == 0 %}
                        No views
                    {% else %}
                        {{ page.views }} view
                    {% endif %}
                </span></li>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <strong>No pages currently in category.</strong>
{% endif %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Registration - Step 2
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Registration - Step 2</h1>
        </div>
    </div>

    <div class="container">
        <div class="row"></div>
        <form method="post" action="{% url 'rango:register_profile' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" type="submit"
                    value="Submit">Create Profile</button>
        </form>
    </div>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Restricted Page
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">{{ message }}</h1>
        </div>
    </div>
{% endblock %}